`ifndef CONTROLLER_ALUOP_DEFINES
`define CONTROLLER_ALUOP_DEFINES
`define CONTROLLER_ALUOP_ADD 3'b000
`define CONTROLLER_ALUOP_OR  3'b001
`define CONTROLLER_ALUOP_XOR 3'b010
`define CONTROLLER_ALUOP_SLT 3'b011
`define CONTROLLER_ALUOP_AND 3'b100
`define CONTROLLER_ALUOP_SUB 3'b101
`define CONTROLLER_ALUOP_FUN 3'b111

`endif


