`ifndef INSTR_DEFINES
`define INSTR_DEFINES
`define INSTR_REG_WIDTH 5
`define INSTR_OP_RANGE 31:26
`define INSTR_RS_RANGE 25:21
`define INSTR_RT_RANGE 20:16
`define INSTR_RD_RANGE 15:11
`define INSTR_SA_RANGE 10:6
`define INSTR_IMM_RANGE 15:0
`define INSTR_INDEX_RANGE 25:0

`define INSTR_INCREMENT 4


`endif